### ISSUE TITLE
Using ILF on EVM bytecode as opposed to Solidity?

### ISSUE THREAD

**Issue by Mikerah** [eth-sri/ilf#10]
Is it possible to run ILF on EVM bytecode as opposed to Solidity? If so, how can this be done?

**Comment by LostBenjamin** [comment]
Hi,

Sorry for the late reply. ILF runs the fuzzing process with EVM Bytecode.

The input contract is in source code. This is because we use `truffle` to build the source and extract the deployment transactions. If the deployment transactions are directly sent to ILF, source code will not be needed. Pull requests are welcomed.

Best,
Jingxuan

**Comment by LostBenjamin** [comment]
close this issue due to inactivity.
